source 'https://rubygems.org'
ruby '2.1.2'
gem 'rails', '4.0.2'

gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'bcrypt-ruby', '~> 3.1.2'
gem 'simple_form'
gem 'friendly_id', '~> 5.0.0'
gem 'figaro'
gem 'active_model_serializers'
gem 'inherited_resources'
gem 'validates_email_format_of'
gem 'omniauth'
gem 'omniauth-facebook', '1.4.0'
gem 'omniauth-twitter'
gem 'newrelic_rpm'
gem 'roo'
gem 'acts_as_list'
gem 'will_paginate'
gem 'delayed_job_active_record'
gem 'kgio'
gem 'memcachier'
gem 'dalli'
gem 'paperclip', '4.2.0'
gem 'delayed_paperclip'
gem 'aws-sdk', '< 2.0'
gem 'httparty'
gem 'stripe'
gem 'validate_url'
gem 'aasm'
gem 'paper_trail', '~> 3.0'
gem 'docverter'
gem "font-awesome-rails"
gem 'ransack'
gem 'doc_raptor'
gem 'has_scope'
gem 'appsignal'
gem 'truncate_html'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'chartkick'
gem 'groupdate'
gem 'filterrific'
gem 'receipts'

group :development do
  gem 'thin'
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'binding_of_caller'
  gem 'nifty-generators'
  gem 'letter_opener'
  gem 'lol_dba'
  # gem 'bullet'
  gem 'annotate', '>=2.6.0'
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'rspec-rails'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'guard-rspec'
  gem 'parallel_tests'
  gem 'jazz_hands', github: 'nixme/jazz_hands', branch: 'bring-your-own-debugger'
  gem 'pry-byebug'   # This may or may not work with 2.1.2 either, so remove if you still get errorrs
end

group :test do
  gem 'faker'
  gem 'capybara'
  gem 'capybara-extensions'
  gem 'shoulda-matchers'
  gem 'launchy'
  gem 'database_cleaner'
  gem 'selenium-webdriver'
  # gem 'poltergeist'
  gem 'mocha'
  gem 'simplecov', require: false
  gem 'stripe-ruby-mock', '~> 1.10.1.7'
end

group :production do
  gem 'rails_12factor'
  gem 'puma'
end
