NUMBER_OF_SPECIALTY_QUESTIONS = 30

POINTS = { 
  correct_answer: 10,
  watched_video: 30,
  answered_user_question: 5,
  accepted_answer: 20,
  upvote: 1
}

PERCENTAGE_MEDICAL_STUDENT = 35
PERCENTAGE_HOUSE_OFFICER = 50
PERCENTAGE_SENIOR_HOUSE_OFFICER = 60
PERCENTAGE_REGISTRAR = 70
PERCENTAGE_CONSULTANT = 80

DASHBOARD_CHART_DAYS = 12

SPECIALTY_UNLOCKS_ALLOWED = 2

PASS_GRADE = 70
