NUMBER_OF_SPECIALTY_QUESTIONS = 30
POINTS_PER_CORRECT_ANSWER = 5
POINTS_PER_WATCHED_VIDEO = 5
POINTS_PER_USER_QUESTION_ANSWERED = 5
POINTS_PER_UPVOTE = 1
POINTS_PER_ACCEPTED_ANSWER = 10
PERCENTAGE_MEDICAL_STUDENT = 35
PERCENTAGE_HOUSE_OFFICER = 50
PERCENTAGE_SENIOR_HOUSE_OFFICER = 60
PERCENTAGE_REGISTRAR = 70
PERCENTAGE_CONSULTANT = 80

DASHBOARD_CHART_DAYS = 12

PASS_GRADE = 70